package com.absences.victor.absences.domains;
// Generated 26-abr-2018 12:02:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Curso generated by hbm2java
 */
@SuppressWarnings("serial")
public class Curso implements java.io.Serializable {

	private Integer idCurso;
	private Ciclo ciclo;
	private String nombre;
	private Date alta;
	private Date baja;

	public Curso() {
	}

	public Curso(Ciclo ciclo, String nombre, Date alta) {
		this.ciclo = ciclo;
		this.nombre = nombre;
		this.alta = alta;
	}

	public Curso(Integer idCurso, Ciclo ciclo, String nombre, Date alta, Date baja) {
		super();
		this.idCurso = idCurso;
		this.ciclo = ciclo;
		this.nombre = nombre;
		this.alta = alta;
		this.baja = baja;
	}

	public Integer getIdCurso() {
		return this.idCurso;
	}

	public void setIdCurso(Integer idCurso) {
		this.idCurso = idCurso;
	}

	public Ciclo getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(Ciclo ciclo) {
		this.ciclo = ciclo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getAlta() {
		return this.alta;
	}

	public void setAlta(Date alta) {
		this.alta = alta;
	}

	public Date getBaja() {
		return this.baja;
	}

	public void setBaja(Date baja) {
		this.baja = baja;
	}
}
