package domain;
// Generated 26-abr-2018 12:02:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
@SuppressWarnings("serial")
public class Alumno implements java.io.Serializable {

	private Integer idAlumno;
	private String nombre;
	private String apellidos;
	private String telefono;
	private String dni;
	private String correo;
	private Date alta;
	private Date baja;

	public Alumno() {
	}

	public Alumno(String nombre, String apellidos, String telefono, String dni, String correo, Date alta) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.dni = dni;
		this.correo = correo;
		this.alta = alta;
	}

	public Alumno(Integer idAlumno, String nombre, String apellidos, String telefono, String dni, String correo,
			Date alta, Date baja) {
		super();
		this.idAlumno = idAlumno;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.dni = dni;
		this.correo = correo;
		this.alta = alta;
		this.baja = baja;
	}

	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public Date getAlta() {
		return this.alta;
	}

	public void setAlta(Date alta) {
		this.alta = alta;
	}

	public Date getBaja() {
		return this.baja;
	}

	public void setBaja(Date baja) {
		this.baja = baja;
	}

	@Override
	public String toString() {
		return "Alumno [idAlumno=" + idAlumno + ", nombre=" + nombre + ", apellidos=" + apellidos + ", telefono="
				+ telefono + ", dni=" + dni + ", correo=" + correo + ", alta=" + alta + ", baja=" + baja + "]";
	}

}
