package domain;
// Generated 26-abr-2018 12:02:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Ciclo generated by hbm2java
 */
@SuppressWarnings("serial")
public class Ciclo implements java.io.Serializable {

	private Integer idCiclo;
	private String nombre;
	private String siglas;
	private Date alta;
	private Date baja;

	public Ciclo() {
	}

	public Ciclo(String nombre, String siglas, Date alta) {
		this.nombre = nombre;
		this.siglas = siglas;
		this.alta = alta;
	}

	public Integer getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(Integer idCiclo) {
		this.idCiclo = idCiclo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSiglas() {
		return this.siglas;
	}

	public void setSiglas(String siglas) {
		this.siglas = siglas;
	}

	public Date getAlta() {
		return this.alta;
	}

	public void setAlta(Date alta) {
		this.alta = alta;
	}

	public Date getBaja() {
		return this.baja;
	}

	public void setBaja(Date baja) {
		this.baja = baja;
	}

}
