package domain;
// Generated 26-abr-2018 12:02:16 by Hibernate Tools 5.2.10.Final

import java.util.Date;

/**
 * Falta generated by hbm2java
 */
@SuppressWarnings("serial")
public class Falta implements java.io.Serializable {

	private Integer idFalta;
	private Date fecha;
	private Alumno alumno;
	private Horario horario;
	private Modulo modulo;
	private Date alta;
	private Date baja;
	
	public Falta() {
	}

	public Falta(Date fecha, Alumno alumno, Horario horario, Modulo modulo, Date alta) {
		this.fecha = fecha;
		this.alumno = alumno;
		this.horario = horario;
		this.modulo = modulo;
		this.alta = alta;
	}

	public Falta(Date fecha, Alumno alumno, Horario horario, Modulo modulo, Date alta, Date baja) {
		this.fecha = fecha;
		this.alumno = alumno;
		this.horario = horario;
		this.modulo = modulo;
		this.alta = alta;
		this.baja = baja;
	}

	public Integer getIdFalta() {
		return this.idFalta;
	}

	public void setIdFalta(Integer idFalta) {
		this.idFalta = idFalta;
	}

	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public Horario getHorario() {
		return this.horario;
	}

	public void setHorario(Horario horario) {
		this.horario = horario;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public Date getAlta() {
		return this.alta;
	}

	public void setAlta(Date alta) {
		this.alta = alta;
	}

	public Date getBaja() {
		return this.baja;
	}

	public void setBaja(Date baja) {
		this.baja = baja;
	}
	

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}


}
